# Generated by Django 4.2.20 on 2025-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockconfiguration',
            name='db_host',
            field=models.CharField(blank=True, help_text='Database host', max_length=255),
        ),
        migrations.AddField(
            model_name='mockconfiguration',
            name='db_name',
            field=models.CharField(blank=True, help_text='Database name', max_length=255),
        ),
        migrations.AddField(
            model_name='mockconfiguration',
            name='db_password',
            field=models.CharField(blank=True, help_text='Database password', max_length=255),
        ),
        migrations.AddField(
            model_name='mockconfiguration',
            name='db_port',
            field=models.CharField(blank=True, default='5432', help_text='Database port', max_length=10),
        ),
        migrations.AddField(
            model_name='mockconfiguration',
            name='db_user',
            field=models.CharField(blank=True, help_text='Database username', max_length=255),
        ),
        migrations.AddField(
            model_name='mockconfiguration',
            name='use_custom_db',
            field=models.BooleanField(default=False, help_text='Use a custom database for cleanup query'),
        ),
    ]
